[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "haashi"
version = "2.0.0"
description = "A modular Python toolkit for reusable utilities."
readme = "README.md"
requires-python = ">=3.10"
license = {text = "MIT"}
authors = [
    {name = "Haashiraaa"}
]
keywords = [  
    "utilities",
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

dependencies = []

[project.optional-dependencies]
dev = [
    "pytest>=7.0.0",
    "black>=23.0.0",
    "mypy>=1.0.0",
    "ruff>=0.1.0",
    "pyright",
    "autopep8"
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

# TODO: Modify urls
[project.urls]
Homepage = "https://github.com/Haashiraaa"
Repository = "https://github.com/Haashiraaa/haashi-analytics-toolkit"
Documentation = "https://github.com/Haashiraaa/haashi-analytics-toolkit/blob/main/README.md"
Issues = "https://github.com/Haashiraaa/haashi-analytics-toolkit/issues"
